export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_SIGNUP_MODAL = 'OPEN_SIGNUP_MODAL';
export const CLOSE_SIGNUP_MODAL = 'CLOSE_SIGNUP_MODAL';
export const OPEN_CHOOSE_SIGNUP_MODAL = 'OPEN_CHOOSE_SIGNUP_MODAL';
export const CLOSE_CHOOSE_SIGNUP_MODAL = 'CLOSE_CHOOSE_SIGNUP_MODAL';
